from dadou_utils.utils_static import AUDIO, ANGLO, BACKWARD, EYES, FORWARD, LEFT, LONG, MODE, MOUTH, NEXT, PLAYLIST, RIGHT, \
    SHORT, WHEELS, NECK, ARMS, LEFT_ARM, RIGHT_ARM, DOWN, UP
from dadouglove.glove_config import IH, IM, IB, MH, MM, MB, AH, AM, AB, OH, OM, OB
from dadouglove.glove_config import DUAL_GLOVE_9DOF_LEFT, DUAL_GLOVE_9DOF_RIGHT, DUAL_GLOVE_LEFT, DUAL_GLOVE_RIGHT, SINGLE_GLOVE_9DOF, SINGLE_GLOVE, \
    DUAL_GLOVE, CONFIG

BUTTONS = "buttons"
RELAY = "relay"
OCTAVER = "octaver"

BUTTONS_LAYOUT = {
    SINGLE_GLOVE_9DOF: {
        IH: {RELAY: OCTAVER}, IM: {RELAY: OCTAVER}, IB: {PLAYLIST: NEXT},
        MH: {LONG: {ANGLO: WHEELS}, SHORT: {AUDIO: 'X'}}, MM: {LONG: {ANGLO: NECK}, SHORT: {AUDIO: 'X'}}, MB: {LONG: {ANGLO: EYES}, SHORT: {AUDIO: 'X'}},
        AH: {LONG: {ANGLO: ARMS}, SHORT: {AUDIO: 'X'}}, AM: {AUDIO: 'X'}, AB: {AUDIO: 'X'},
        OH: {MODE: NEXT}, OM: {PLAYLIST: UP}, OB: {PLAYLIST: DOWN}
    },
    SINGLE_GLOVE: {
        IH: {RELAY: OCTAVER}, IM: {RELAY: OCTAVER}, IB: {PLAYLIST: NEXT},
        MH: {LONG: {WHEELS: FORWARD}, SHORT: {AUDIO: 'X'}}, MM: {LONG: {WHEELS: BACKWARD}, SHORT: {AUDIO: 'X'}}, MB: {LONG: {ANGLO: EYES}, SHORT: {AUDIO: 'X'}},
        AH: {LONG: {WHEELS: LEFT}, SHORT: {AUDIO: 'X'}}, AM: {LONG: {WHEELS: RIGHT}, SHORT: {AUDIO: 'X'}}, AB: {AUDIO: 'X'},
        OH: {MODE: NEXT}, OM: {PLAYLIST: UP}, OB: {PLAYLIST: DOWN}
    },
    DUAL_GLOVE_9DOF_LEFT: {
        IH: {AUDIO: 'X'}, IM: {AUDIO: 'X'}, IB: {AUDIO: 'X'},
        MH: {LONG: {ANGLO: EYES}, SHORT: {AUDIO: 'X'}}, MM: {LONG: {ANGLO: LEFT_ARM}, SHORT: {AUDIO: 'X'}}, MB: {LONG: {ANGLO: EYES}, SHORT: {AUDIO: 'X'}},
        AH: {LONG: {WHEELS: LEFT}, SHORT: {AUDIO: 'X'}}, AM: {LONG: {WHEELS: RIGHT}, SHORT: {AUDIO: 'X'}}, AB: {AUDIO: 'X'},
        OH: {MODE: NEXT}, OM: {PLAYLIST: UP}, OB: {PLAYLIST: DOWN}
    },
    DUAL_GLOVE_9DOF_RIGHT: {
        IH: {RELAY: OCTAVER}, IM: {RELAY: OCTAVER}, IB: {PLAYLIST: NEXT},
        MH: {LONG: {ANGLO: WHEELS}, SHORT: {AUDIO: 'X'}}, MM: {LONG: {ANGLO: RIGHT_ARM}, SHORT: {AUDIO: 'X'}}, MB: {LONG: {ANGLO: MOUTH}, SHORT: {AUDIO: 'X'}},
        AH: {LONG: {WHEELS: LEFT}, SHORT: {AUDIO: 'X'}}, AM: {LONG: {WHEELS: RIGHT}, SHORT: {AUDIO: 'X'}}, AB: {AUDIO: 'X'},
        OH: {MODE: NEXT}, OM: {PLAYLIST: UP}, OB: {PLAYLIST: DOWN}
    },
    DUAL_GLOVE_LEFT: {
        IH: {RELAY: OCTAVER}, IM: {RELAY: OCTAVER}, IB: {PLAYLIST: NEXT},
        MH: {LONG: {WHEELS: FORWARD}, SHORT: {AUDIO: 'X'}}, MM: {LONG: {WHEELS: BACKWARD}, SHORT: {AUDIO: 'X'}}, MB: {LONG: {ANGLO: EYES}, SHORT: {AUDIO: 'X'}},
        AH: {LONG: {WHEELS: LEFT}, SHORT: {AUDIO: 'X'}}, AM: {LONG: {WHEELS: RIGHT}, SHORT: {AUDIO: 'X'}}, AB: {AUDIO: 'X'},
        OH: {MODE: NEXT}, OM: {PLAYLIST: UP}, OB: {PLAYLIST: DOWN}
    },
    DUAL_GLOVE_RIGHT: {
        IH: {RELAY: OCTAVER}, IM: {RELAY: OCTAVER}, IB: {PLAYLIST: NEXT},
        MH: {LONG: {WHEELS: FORWARD}, SHORT: {AUDIO: 'X'}}, MM: {LONG: {WHEELS: BACKWARD}, SHORT: {AUDIO: 'X'}}, MB: {LONG: {ANGLO: EYES}, SHORT: {AUDIO: 'X'}},
        AH: {LONG: {WHEELS: LEFT}, SHORT: {AUDIO: 'X'}}, AM: {LONG: {WHEELS: RIGHT}, SHORT: {AUDIO: 'X'}}, AB: {AUDIO: 'X'},
        OH: {MODE: NEXT}, OM: {PLAYLIST: UP}, OB: {PLAYLIST: DOWN}
    }
}


